
#ifndef MYFORCESNLPSOLVER_CASADI_H
#define MYFORCESNLPSOLVER_CASADI_H

/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

int myForcesNLPSolver_objective_1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);

void myForcesNLPSolver_objective_1_incref(void);

const casadi_int* myForcesNLPSolver_objective_1_sparsity_out(casadi_int i);

int myForcesNLPSolver_dynamics_1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);

void myForcesNLPSolver_dynamics_1_incref(void);

const casadi_int* myForcesNLPSolver_dynamics_1_sparsity_out(casadi_int i);

int myForcesNLPSolver_inequalities_1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);

void myForcesNLPSolver_inequalities_1_incref(void);

const casadi_int* myForcesNLPSolver_inequalities_1_sparsity_out(casadi_int i);

int myForcesNLPSolver_objective_51(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);

void myForcesNLPSolver_objective_51_incref(void);

const casadi_int* myForcesNLPSolver_objective_51_sparsity_out(casadi_int i);

#ifdef __cplusplus
} /* extern "C" */
#endif
#endif
