/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) myForcesNLPSolver_casadi_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_f3 CASADI_PREFIX(f3)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#if 0
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[9] = {5, 1, 0, 5, 0, 1, 2, 3, 4};
static const casadi_int casadi_s1[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s4[12] = {1, 5, 0, 1, 2, 2, 3, 4, 0, 0, 0, 0};
static const casadi_int casadi_s5[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s6[18] = {3, 5, 0, 1, 2, 5, 7, 10, 0, 1, 0, 1, 2, 0, 1, 0, 1, 2};
static const casadi_int casadi_s7[10] = {1, 5, 0, 1, 2, 2, 2, 2, 0, 0};
static const casadi_int casadi_s8[8] = {1, 3, 0, 1, 2, 2, 0, 0};

/* myForcesNLPSolver_objective_1:(i0[5],i1[4],i2[],i3[])->(o0,o1[1x5,4nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a2, a3, a4, a5, a6, a7, a8, a9;
    a0=1.0000000000000000e-002;
    a1=arg[0]? arg[0][3] : 0;
    a2=casadi_sq(a1);
    a3=arg[0]? arg[0][4] : 0;
    a4=casadi_sq(a3);
    a2=(a2+a4);
    a2=(a0*a2);
    a4=1.0000000000000001e-001;
    a5=arg[0]? arg[0][0] : 0;
    a6=casadi_sq(a5);
    a7=arg[0]? arg[0][1] : 0;
    a8=6.;
    a8=(a7-a8);
    a9=casadi_sq(a8);
    a6=(a6+a9);
    a6=(a4*a6);
    a2=(a2+a6);
    a6=1.0000000000000000e-003;
    a9=arg[1]? arg[1][1] : 0;
    a9=(a5-a9);
    a10=casadi_sq(a9);
    a11=arg[1]? arg[1][2] : 0;
    a7=(a7-a11);
    a11=casadi_sq(a7);
    a10=(a10+a11);
    a10=(a6*a10);
    a2=(a2+a10);
    if (res[0]!=0) res[0][0]=a2;
    a9=(a9+a9);
    a9=(a6*a9);
    a5=(a5+a5);
    a5=(a4*a5);
    a9=(a9+a5);
    if (res[1]!=0) res[1][0]=a9;
    a7=(a7+a7);
    a6=(a6*a7);
    a8=(a8+a8);
    a4=(a4*a8);
    a6=(a6+a4);
    if (res[1]!=0) res[1][1]=a6;
    a1=(a1+a1);
    a1=(a0*a1);
    if (res[1]!=0) res[1][2]=a1;
    a3=(a3+a3);
    a0=(a0*a3);
    if (res[1]!=0) res[1][3]=a0;
    return 0;
}

int myForcesNLPSolver_objective_1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
    return casadi_f0(arg, res, iw, w, mem);
}

const casadi_int* myForcesNLPSolver_objective_1_sparsity_out(casadi_int i) {
    switch (i) {
        case 0: return casadi_s3;
        case 1: return casadi_s4;
        default: return 0;
    }
}

/* myForcesNLPSolver_dynamics_1:(i0[5],i1[4],i2[],i3[])->(o0[3],o1[3x5,10nz]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4, a5, a6, a7, a8, a9;
    a0=arg[0]? arg[0][0] : 0;
    a1=1.0000000000000001e-001;
    a2=arg[0]? arg[0][3] : 0;
    a3=arg[0]? arg[0][2] : 0;
    a4=5.0000000000000003e-002;
    a5=arg[0]? arg[0][4] : 0;
    a6=(a4*a5);
    a6=(a3+a6);
    a7=cos(a6);
    a8=(a2*a7);
    a8=(a1*a8);
    a0=(a0+a8);
    if (res[0]!=0) res[0][0]=a0;
    a0=arg[0]? arg[0][1] : 0;
    a8=sin(a6);
    a9=(a2*a8);
    a9=(a1*a9);
    a0=(a0+a9);
    if (res[0]!=0) res[0][1]=a0;
    a5=(a1*a5);
    a3=(a3+a5);
    if (res[0]!=0) res[0][2]=a3;
    a3=1.;
    if (res[1]!=0) res[1][0]=a3;
    if (res[1]!=0) res[1][1]=a3;
    a5=sin(a6);
    a0=(a2*a5);
    a0=(a1*a0);
    a0=(-a0);
    if (res[1]!=0) res[1][2]=a0;
    a6=cos(a6);
    a0=(a2*a6);
    a0=(a1*a0);
    if (res[1]!=0) res[1][3]=a0;
    if (res[1]!=0) res[1][4]=a3;
    a7=(a1*a7);
    if (res[1]!=0) res[1][5]=a7;
    a8=(a1*a8);
    if (res[1]!=0) res[1][6]=a8;
    a5=(a4*a5);
    a5=(a2*a5);
    a5=(a1*a5);
    a5=(-a5);
    if (res[1]!=0) res[1][7]=a5;
    a4=(a4*a6);
    a2=(a2*a4);
    a2=(a1*a2);
    if (res[1]!=0) res[1][8]=a2;
    if (res[1]!=0) res[1][9]=a1;
    return 0;
}

int myForcesNLPSolver_dynamics_1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
    return casadi_f1(arg, res, iw, w, mem);
}

const casadi_int* myForcesNLPSolver_dynamics_1_sparsity_out(casadi_int i) {
    switch (i) {
        case 0: return casadi_s5;
        case 1: return casadi_s6;
        default: return 0;
    }
}

/* myForcesNLPSolver_inequalities_1:(i0[5],i1[4],i2[],i3[])->(o0,o1[1x5,2nz]) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3;
    a0=arg[0]? arg[0][0] : 0;
    a1=arg[1]? arg[1][1] : 0;
    a0=(a0-a1);
    a1=casadi_sq(a0);
    a2=arg[0]? arg[0][1] : 0;
    a3=arg[1]? arg[1][2] : 0;
    a2=(a2-a3);
    a3=casadi_sq(a2);
    a1=(a1+a3);
    a3=arg[1]? arg[1][3] : 0;
    a3=casadi_sq(a3);
    a1=(a1-a3);
    if (res[0]!=0) res[0][0]=a1;
    a0=(a0+a0);
    if (res[1]!=0) res[1][0]=a0;
    a2=(a2+a2);
    if (res[1]!=0) res[1][1]=a2;
    return 0;
}

int myForcesNLPSolver_inequalities_1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
    return casadi_f2(arg, res, iw, w, mem);
}

const casadi_int* myForcesNLPSolver_inequalities_1_sparsity_out(casadi_int i) {
    switch (i) {
        case 0: return casadi_s3;
        case 1: return casadi_s7;
        default: return 0;
    }
}

/* myForcesNLPSolver_objective_51:(i0[3],i1[4],i2[],i3[])->(o0,o1[1x3,2nz]) */
static int casadi_f3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4, a5, a6, a7, a8;
    a0=1.0000000000000001e-001;
    a1=arg[0]? arg[0][0] : 0;
    a2=casadi_sq(a1);
    a3=arg[0]? arg[0][1] : 0;
    a4=6.;
    a4=(a3-a4);
    a5=casadi_sq(a4);
    a2=(a2+a5);
    a2=(a0*a2);
    a5=1.0000000000000000e-003;
    a6=arg[1]? arg[1][1] : 0;
    a6=(a1-a6);
    a7=casadi_sq(a6);
    a8=arg[1]? arg[1][2] : 0;
    a3=(a3-a8);
    a8=casadi_sq(a3);
    a7=(a7+a8);
    a7=(a5*a7);
    a2=(a2+a7);
    if (res[0]!=0) res[0][0]=a2;
    a1=(a1+a1);
    a1=(a0*a1);
    a6=(a6+a6);
    a6=(a5*a6);
    a1=(a1+a6);
    if (res[1]!=0) res[1][0]=a1;
    a4=(a4+a4);
    a0=(a0*a4);
    a3=(a3+a3);
    a5=(a5*a3);
    a0=(a0+a5);
    if (res[1]!=0) res[1][1]=a0;
    return 0;
}

int myForcesNLPSolver_objective_51(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
    return casadi_f3(arg, res, iw, w, mem);
}

const casadi_int* myForcesNLPSolver_objective_51_sparsity_out(casadi_int i) {
    switch (i) {
        case 0: return casadi_s3;
        case 1: return casadi_s8;
        default: return 0;
    }
}

#ifdef __cplusplus
} /* extern "C" */
#endif
